[postgres]
host = "postgres host"
port = "5432"
user = "user"
password = "user"
db = "db name"

[server]
port = "80"

[nft-server]
address = "http://your-nft-metadata-service:80"

[node]
address = "http://your-blockchain-node:80"

[auth]
enabled = true
admin_public_key = "admins rsa public key"
